### ISSUE TITLE
CORS error when querying data

### ISSUE THREAD

**Issue by lollobaldo** [InfluxCommunity/influxdb3-js#101]
### Specifications

* Client Version: "@influxdata/influxdb3-client": "^0.2.0"
* InfluxDB Version: v3
* Platform: Browser

Hi, when querying an influxdb on cloud2.influxdata.com, I receive a CORS error when connecting.
Connections worked fine earlier when using the
`https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/query?orgID=???` endpoint, but now fail with the library using `https://eu-central-1-1.aws.cloud2.influxdata.com/arrow.flight.protocol.FlightService/DoGet`

Is there some setup I should to on inflixdb cloud?

### Code sample to reproduce problem

```csharp
```

### Expected behavior

Normal connection

### Actual behavior

Connect and fetch data without CORS error

**Comment by Sciator** [comment]
Hi @lollobaldo,

thanks for using our client. 

Unfortunately, the current version of the browser requires the use of an envoy proxy to modify the connection to be able to comunicate with arrow flight endpoints.

Furthermore, when encountering CORS issues, it's optimal to exclusively interact with the server that supplies you with the HTML files. You can setup proxy to envoy on any server. It's VITE dev server in our browser example. On this server you can then setup proxy which will forward your communication to envoy which forwards it to influxdb.

Example setup:

[Browser code](https://github.com/InfluxCommunity/influxdb3-js/blob/4b9a2fd597637ec54b6bfb5ab23556797743600a/examples/browser/src/main.ts#L45):
```ts
const host = '/influx' // vite proxy

const client = new InfluxDBClient({host, token})
```

[Vite config](https://github.com/InfluxCommunity/influxdb3-js/blob/4b9a2fd597637ec54b6bfb5ab23556797743600a/examples/browser/vite.config.ts#L1C1-L13C3):
```ts
import {defineConfig} from 'vite'

export default defineConfig({
  server: {
    proxy: {
      '/influx': {
        target: 'http://localhost:10000/', // envoy proxy address
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/influx/, ''),
      },
    },
  },
})
```

Rest is handled in [envoy](https://github.com/InfluxCommunity/influxdb3-js/blob/4b9a2fd597637ec54b6bfb5ab23556797743600a/examples/browser/envoy.yaml#L52) on port 10000

Have you tried out the new browser example ? We recommend try to run our example first.

If you have still problems running client in browser, please provide more information.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
