### ISSUE TITLE
browser: socket timeout property appears to be ignored 

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-js#214]
### Specifications

* Client Version: 0.5.0
* InfluxDB Version: IOX
* Platform: Ubuntu 22.04, Nodejs 21.4, Vite 4.4.12

### Code sample to reproduce problem

Note, if the timeout length seems unreal, this is code from an exploratory test.  Wanted to check that the timeout property is being used. 

```js
        client = new InfluxDBClient({host: HOST, token: TOKEN, timeout: 10})
```

### Expected behavior

Expected a timeout exception to be thrown.  

Note that in a similar test of the nodejs version of the library an exception is thrown. 

### Actual behavior

All writes succeed.  It appears the `timeout` property is ignored.  Even nonsensical values like `-10` are neither caught as out of range nor are they used in any way.

**Comment by alespour** [comment]
This is unfortunately correct behavior, in browser, socket-level access is not accessible. I've changed the `timeout` property doc to explicitly state that.
