### ISSUE TITLE
Add Headers to HttpError

### ISSUE THREAD

**Issue by PrestonGiorgianni** [InfluxCommunity/influxdb3-js#357]
### Use Case

The api [documentation](https://docs.influxdata.com/influxdb/cloud/api/v2/#tag/Response-codes:~:text=the%20request%20quota.-,The%20Retry%2DAfter%20header%20describes%20when%20to%20try%20the%20request%20again.,-500) for the api indicates that when you get a 429 rate limit, you should look at the Retry-After to determine when to try the request again. Currently `influxClient.write` will throw an error on 429 status codes, but I do not have access to this header to know how long to wait before a retry.

### Expected behavior

```ts
try {
  influxClient.write(...)
} catch(error) {
  if (error instanceof HttpError && error.statusCode === 429) {
    error.headers['Retry-After'] !== undefined; //should be truthy
    // some back off logic based on error.headers['Retry-After']
  }
}
```

### Actual behavior

```ts
try {
  influxClient.write(...)
} catch(error) {
  if (error instanceof HttpError && error.statusCode === 429) {
    error.headers['Retry-After'] !== undefined; //is falsy
    // some back off logic based on error.headers['Retry-After']
  }
}
```

**Comment by bednar** [comment]
Hi @PrestonGiorgianni,

Thank you for reporting this. We will address it as soon as possible.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards
