### ISSUE TITLE
Browser client example link is broken

### ISSUE THREAD

**Issue by suyashcjoshi** [InfluxCommunity/influxdb3-js#384]
### Specifications

Please note that the link to [IOx inside browser example](https://github.com/InfluxCommunity/influxdb3-js/blob/f841deff683e6a93fefb1e5b98f7ce463d370c7d/examples/browser/src/index.ts) on this [page](https://github.com/InfluxCommunity/influxdb3-js/blob/HEAD/examples/browser/README.md) is not working: https://github.com/InfluxCommunity/influxdb3-js/blob/f841deff683e6a93fefb1e5b98f7ce463d370c7d/examples/browser/src/index.ts

### Code sample to reproduce problem

see description above

### Expected behavior

Page should show up

### Actual behavior

404 error

**Comment by bednar** [comment]
Thanks for reporting this, @suyashcjoshi.
