### ISSUE TITLE
Write/Query functions: database vs org + bucket

### ISSUE THREAD

**Issue by lmangani** [InfluxCommunity/influxdb3-js#48]
### Specifications

* Client Version: v0.1.0
* InfluxDB Version: IOx GIT
* Platform: Linux/x86

## Summary

First and foremost, thanks for creating and pushing this out! 🥳 The client works but the instructions are slightly off. 

The `write` function àppears to require both `org` and `bucket` parameters to work as intended, together forming the `database` variable hypothetically would be used by `query` function. 

## Write function

The write function is declared as follows in the example:
```
await client.write(p, database)
```

IOx returns an error when the `org` parameter is omitted: `'{"code":"invalid","message":"missing org/bucket value"}'`

The following syntax works as intended:

```
await client.write(p, bucket, org)
```

Since those are not declared, an additional line in the README should be perhaps added?
```
const url = process.env.INFLUXDB_URL
const token = process.env.INFLUXDB_TOKEN
const database = process.env.INFLUXDB_DATABASE // "company_stats"
const [org, bucket] = database.split('_');
```

## Query function

-  The query part uses database, which I assume would/should equal  `org`_`bucket` as in most IOx examples both are utilized, but this doesn't seem to be the case with this example and implementation. Is this a valid or null concern? The iox documentation states as follows:
```
 IOx maps organization and bucket pairs to namespaces with the two parts separated by an underscore (_): organization_bucket.
``` 

-  The query README is missing the `queryType` parameter

```
const queryResult = client.query(query, database, queryType)
```

### Working Example with notes (working with local IOx)

```javascript

const {InfluxDBClient, Point} = require('@influxdata/influxdb3-client');

const token = "abc123"
const database = "company_stats"
const [org, bucket] = database.split('_');

async function main() {
    await insert()
    await query()
}

main()

async function insert(){
        // The same client cannot be used for reading/writing when using a local IOx setup
        const host = "http://localhost:8080"
        const client = new InfluxDBClient({host, token})
        const line = `stat,unit=temperature avg=20.5,max=45.0`

        // The org and bucket are both required by function when using a local IOx setup
        await client.write(line, bucket, org)

        client.close()
}

async function query(){
        // The same client cannot be used for reading/writing when using a local IOx setup
        const host = "http://localhost:8082"
        const client = new InfluxDBClient({host, token })
        // Execute query
        const query = `
            SELECT *
            FROM "stat"
            WHERE
            time >= now() - interval '5 minute'
            AND
            "unit" IN ('temperature')
        `
        // The database ( = org + bucket) is required by the query function, inconsistently with write client.
        const queryType = 'sql'
        const queryResult = await client.query(query, database, queryType)

        for await (const row of queryResult) {
            console.log(`avg is ${row.avg}`)
            console.log(`max is ${row.max}`)
        }
        client.close()

}

```

### Additional info

Are `org` parameters perhaps not needed when using InfluxDB cloud? In a local IOx setup, they most definitely are. 
I was about to submit a PR but I'm not 100% if this is inline with the intended usecase.

Thanks a million!

**Comment by bednar** [comment]
Hi @lmangani,

Thank you for your issue and PR.

The current client implementation is primarily focused on InfluxDB Cloud and hasn't been tested with IOx. Dependence on IOx could potentially introduce future incompatibilities with the client because IOx is not yet stable.

> The query README is missing the queryType parameter.

The default query type is SQL.

> Are org parameters perhaps not needed when using InfluxDB cloud?

Yes, it is automatically retrieved from the token.

Given the current state of IOx, the best solution would be to create a new example for connecting to IOx.

I apologize for any troubles and thank you for evaluating our first client version.

Cheers

**Comment by lmangani** [comment]
Thanks @bednar this makes lots of sense. I think you're right, this can easily be solved by having two examples or some side notes. And there's no trouble, quite the opposite - lots of fun! With the proper adjustments the driver works great and we'll do some capacity testing and provide feedback.

**Comment by bednar** [comment]
> With the proper adjustments the driver works great and we'll do some capacity testing and provide feedback.

That's fantastic 👏 This will be incredibly useful for us!
