### ISSUE TITLE
Cannot use `Point` to correctly assign timestamp

### ISSUE THREAD

**Issue by bcorbett6** [InfluxCommunity/influxdb3-js#51]
### Specifications

* Client Version: 0.1.0
* InfluxDB Version: Cloud Serverless 3.0, https://us-east-1-1.aws.cloud2.influxdata.com

### Code sample to reproduce problem

```js
    const newMeasurement = new Point(measurementTo)
        .timestamp(1687953601688) // Any value here results in the same timestamp appearing in Cloud Serverless
        .tag('device_id', 'testId3')
        .floatField('avgEnergy', 120.10)
    await client.write(newMeasurement, databaseTo)
```
Any value for timestamp results in 1970-01-01T00:28:07.953Z being written as the timestamp. I've tested with 3 different write operations with completely different data

### Expected behavior

The specified timestamp is against the record in InfluxDB

### Actual behavior

1970-01-01T00:28:07.953Z is the timestamp on all tests

**Comment by bednar** [comment]
Hi @bcorbett6,

your timestamp `1687953601688` is in milliseconds precision. You have to initialize your client with proper precision:

```typescript
const client = new InfluxDBClient({host, token, writeOptions: {precision: 'ms'}})
```

Regards

**Comment by bcorbett6** [comment]
Thank you for the quick response, this was spot on @bednar !
